export enum ROUTES {
	HOME_TABS = "HOME_TABS",
	AUTH_PROMPT = "AUTH_PROMPT",
	HAS_CONTRACT = "HAS_CONTRACT",
	APPLICATION = "APPLICATION",
	APPLICATION_FORM = "APPLICATION_FORM",
	LOGIN = "LOGIN",
	REGISTER = "REGISTER",
	PINCODE = "PINCODE",

	// Tabs Navigation ......

	PERSONAL = "PERSONAL",
	INFARMATION = "INFARMATION",
	NOTIFICATION = "NOTIFICATION",
	CANCEL = "CANCEL",
	DATA = "DATA",
	QRKOD = "QRKOD",
	TOORDER = 'TOORDER',
	TOORDER2 = 'TOORDER2',
	ADDITIONAL = "ADDITIONAL"
}
